name: learning_language_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  audioplayers: ^6.0.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/imaes/colors/
    - assets/imaes/family/
    - assets/imaes/numbers/
    - assets/imaes/Private_Image/
    - assets/sounds/colors/
    - assets/sounds/family/
    - assets/sounds/numbers/
    - assets/sounds/phrases/